- name: Enable interface and assign ip
  hosts: asa1
  gather_facts: no
  become: yes
  tasks:
    - name: add ASA interface to configuration
      asa_config:
        lines:
          - interface GigabitEthernet0/0

    - name: configure ASA interface parameters
      asa_config:
        lines:
          - nameif external
          - security-level 50
          - ip address 192.168.121.101 255.255.255.0
        parents: "interface GigabitEthernet0/0"
