- hosts: router1
  gather_facts: no
  connection: network_cli
  become: true
  vars:
    acl_name: ANSIBLE-TEST
    comment: test_acl_1
    ip_address: 192.168.121.159


  tasks:
    - name: Reorder current ACL so new entry can be added at right position
      ios_config:
          lines:
            - remark {{comment}}
            - deny ip host {{ip_address}} any log
          parents: ip access-list extended {{acl_name}}


    - ios_config:
          lines:
            - ip access-group {{acl_name}} in
          parents: interface FastEthernet 1/0
